version: "3"

services:
  app:
    image: sveltekit-docker
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000